import { Breadcrumb, Typography, Collapse, Layout } from 'antd';
import Link from 'next/link'

import styles from '../styles/faq.module.css'
import BuyTag from '../components/BuyTag'
import SellTag from '../components/SellTag'
import HodlTag from '../components/HodlTag'

const { Title, Paragraph } = Typography;
const { Panel } = Collapse;
const { Content } = Layout;

export default function Faq() {
  return (
    <Content className={styles.content}>
      <Breadcrumb className={styles.breadcrumbs}>
        <Breadcrumb.Item><Link href="/"><a>Home</a></Link></Breadcrumb.Item>
        <Breadcrumb.Item>FAQ</Breadcrumb.Item>
      </Breadcrumb>
      <Title>FAQ</Title>
      <Paragraph type="secondary" className={styles.subTitle}>Find answers to your frequently asked questions here.</Paragraph>
      <Collapse defaultActiveKey={['0']} accordion>
        <Panel header="What is CoinRotator?" key="0">
          <p>CoinRotator is a crypto market screener for the top 1000 crypto coins. When you land on the homepage you will see the coins ranked by market cap. Each coin (excluding stablecoins) will have a signal to <BuyTag /> <SellTag /> or <HodlTag />. This is determined once daily at 00:00 UTC. The signals are generated by checking the altcoin against BTC ETH and USDT. If a coin is stronger than these three it will have a <BuyTag />, if it is weaker it is a <SellTag />. And if it is inconclusive the signal generated is <HodlTag />.</p>
        </Panel>
        <Panel header="How do you use CoinRotator?" key="1">
          <p>There are several ways CoinRotator will become an indispensable part of your daily Crypto trading routine.</p>
          <ol>
            <li>Check for new signals daily in order to buy into coins which are outperforming BTC ETH and USDT. After checking the news, general health of the market, you can take a position and check its performance daily. The CoinRotator screener currently updates once per day at 00:00 UTC.</li>
            <li>Search your favorite altcoin in the top 1000 (based on market cap) and see if it is a <BuyTag /> <SellTag /> and <HodlTag />. Consider your time horizon and profit expectations. If you are in profit, consider taking some profits based on what the CoinRotator signal reports.</li>
            <li>Seek out undervalued low marketcap coins by applying advanced settings in the filter. Choose &lt;100m and signal streak 1-5 and select Buy only. Here will be a screen result of the best performing small marketcap coins in the top 1000. Be warned, these coins are more volatile than the top ranked coins but if BTC behaves you will see much larger gains in our experience.</li>
          </ol>
        </Panel>
        <Panel header="Does CoinRotator work in bear markets?" key="2">
          <p>Yes! CoinRotator provides three forms of signals. <BuyTag />, <HodlTag />, and <SellTag />. When Bitcoin is weak, sell signals are better than buy signals. Be advised shorting crypto is as risky as it gets. You can lose more than your entire investment if you are overleveraged.</p>
        </Panel>
        <Panel header="What are Signals based on?" key="3">
          <p>Primarily on the SuperTrend indicator. CoinRotator&apos;s default settings are faster than the respective indicator found on Tradingview. In addition we track the performance of the altcoin against BTC ETH and USDT. An actionable signal is only generated if all three markets are in agreement. If not, a <HodlTag /> signal is issued.</p>
        </Panel>
        <Panel header="How accurate are Signals?" key="4">
          <p>They are not designed to be a complete trading system. You&apos;ll need to check the trend health of the overall market before taking any position. Check out the Twitter feed for your chosen coin (found on the coin pages), and then check Bitcoin. If things look positive (or excessively negative, for that matter), it&apos;s a likely winner.</p>
        </Panel>
        <Panel header="How to Apply the Supertrend indicator to the Coin Page Chart?" key="5">
          <ol className={styles.imageList}>
            { /* eslint-disable @next/next/no-img-element */ }
            <li>Click on indicators<img src="/supertrend1.png" alt="Click on indicators"/></li>
            <li>Type Supertrend<img src="/supertrend2.png" alt="Type 'SuperTrend'" /></li>
            <li>Change settings to ATR length 5 and Factor to 1.5 for CoinRotator settings.<img src="/supertrend3.png" alt="Change the settings" /></li>
            { /* eslint-enable @next/next/no-img-element */ }
          </ol>
          <p>If you prefer to use the default Supertrend settings in the screener you can do so in the advanced filter on the homepage.</p>
        </Panel>
        <Panel header="Do you have any backtest data?" key="6">
          <p>We have personal experience with these signals for several years in the crypto market. They work, but not as a stand alone system. They are very powerful as a filtering mechanism (don’t fight their trend). We will begin publishing individual market performance for each altcoin in Q1 2022.</p>
        </Panel>
        <Panel header="Can we access your API?" key="7">
          <p>Q1 2022</p>
        </Panel>
        <Panel header="Why does my coin say 'Buy', but it's down a lot today?" key="8">
          <p>Coinrotator issues signals once a day after the daily bar closes at 00:00 UTC. The price must violate the price threshold and stay at that point after this time. Once that happens the signal will reverse. At present we strongly discourage day trading based on the screener.</p>
        </Panel>
      </Collapse>
    </Content>);
}