import { Breadcrumb, Typography, Collapse, Layout } from 'antd';
import Link from 'next/link'

import baseStyles from '../styles/base.module.less';
import faqStyles from '../styles/faq.module.less'

import UpTag from '../components/UpTag'
import DownTag from '../components/DownTag'
import HodlTag from '../components/HodlTag'
import globalData from '../lib/globalData';

const { Title, Paragraph } = Typography;
const { Panel } = Collapse;
const { Content } = Layout;

export default function Faq() {
  return (
    <Content className={baseStyles.container}>
      <Breadcrumb className={baseStyles.breadcrumbs}>
        <Breadcrumb.Item><Link href="/"><a>Home</a></Link></Breadcrumb.Item>
        <Breadcrumb.Item>FAQ</Breadcrumb.Item>
      </Breadcrumb>
      <Title className={baseStyles.title}>FAQ</Title>
      <Paragraph type="secondary" className={baseStyles.subTitle}>Find answers to your frequently asked questions here.</Paragraph>
      <Collapse defaultActiveKey={['0']} accordion>
        <Panel header="What is CoinRotator?" key="0">
          CoinRotator is a crypto market screener for the top 1000 crypto coins. When you land on the homepage you will see the coins ranked by market cap. Each coin (excluding stablecoins) will have an <UpTag /> <DownTag /> or <HodlTag /> trend. This is determined once daily at 00:00 UTC. The trends are generated by checking the altcoin against BTC ETH and USDT. If a coin is stronger than these three it will be an <UpTag /> trend, if it is weaker it is a <DownTag /> trend. And if it is inconclusive the trend generated is <HodlTag /> trend.
        </Panel>
        <Panel header="How do you use CoinRotator?" key="1">
          <p>There are several ways CoinRotator will become an indispensable part of your daily Crypto trading routine.</p>
          <ol>
            <li>Check for new trends daily in order to buy into coins which are outperforming BTC ETH and USDT. After checking the news, general health of the market, you can take a position and check its performance daily. The CoinRotator screener currently updates once per day at 00:00 UTC.</li>
            <li>Search your favorite altcoin in the top 1000 (based on market cap) and see if it is a <UpTag /> <DownTag /> and <HodlTag /> trend. Consider your time horizon and profit expectations. If you are in profit, consider taking some profits based on what the CoinRotator trend reports.</li>
            <li>Seek out undervalued low marketcap coins by applying advanced settings in the filter. Choose &lt;100m and trend streak 1-5 and select UP only. Here will be a screen result of the best performing small marketcap coins in the top 1000. Be warned, these coins are more volatile than the top ranked coins but if BTC behaves you will see much larger gains in our experience.</li>
          </ol>
        </Panel>
        <Panel header="Does CoinRotator work in bear markets?" key="2">
          Yes! CoinRotator provides three forms of trends. <UpTag />, <HodlTag />, and <DownTag />. When Bitcoin is weak, down trends are better than up trends. Be advised shorting crypto is as risky as it gets. You can lose more than your entire investment if you are overleveraged.
        </Panel>
        <Panel header="What are Trends based on?" key="3">
          Primarily on the SuperTrend indicator. CoinRotator&apos;s default settings are faster than the respective indicator found on Tradingview. In addition we track the performance of the altcoin against BTC ETH and USDT. An actionable trend is only generated if all three markets are in agreement. If not, a <HodlTag /> trend is issued.
        </Panel>
        <Panel header="How accurate are Trends?" key="4">
          They are not designed to be a complete trading system. You&apos;ll need to check the trend health of the overall market before taking any position. Check out the Twitter feed for your chosen coin (found on the coin pages), and then check Bitcoin. If things look positive (or excessively negative, for that matter), it&apos;s a likely winner.
        </Panel>
        <Panel header="How to Apply the Supertrend indicator to the Coin Page Chart?" key="5">
          <ol className={faqStyles.imageList}>
            { /* eslint-disable @next/next/no-img-element */ }
            <li>Click on indicators<img src="/supertrend1.png" alt="Click on indicators"/></li>
            <li>Type Supertrend<img src="/supertrend2.png" alt="Type 'SuperTrend'" /></li>
            <li>Change settings to ATR length 5 and Factor to 1.5 for CoinRotator settings.<img src="/supertrend3.png" alt="Change the settings" /></li>
            { /* eslint-enable @next/next/no-img-element */ }
          </ol>
          If you prefer to use the default Supertrend settings in the screener you can do so in the advanced filter on the homepage.
        </Panel>
        <Panel header="Do you have any backtest data?" key="6">
          We have personal experience with these trends for several years in the crypto market. They work, but not as a stand alone system. They are very powerful as a filtering mechanism (don’t fight their trend). We will begin publishing individual market performance for each altcoin in Q2 2022.
        </Panel>
        <Panel header="Can we access your API?" key="7">
          Q2 2022
        </Panel>
        <Panel header="Why does my coin say 'Up', but it's down a lot today?" key="8">
          Coinrotator issues trends once a day after the daily bar closes at 00:00 UTC. The price must violate the price threshold and stay at that point after this time. Once that happens the trends will reverse. At present we strongly discourage blindly following the trend alerts based on the screener.
        </Panel>
      </Collapse>
    </Content>);
}

export async function getStaticProps() {
  const appData = await globalData();

  return { props: { appData } };
}
