import { Typography, Collapse, Layout } from 'antd';
import Link from 'next/link'

import baseStyles from "../styles/base.module.less";
import faqStyles from "../styles/faq.module.less"

import UpTag from '../components/UpTag'
import DownTag from '../components/DownTag'
import HodlTag from '../components/HodlTag'
import PageHeader from '../components/PageHeader'
import globalData from '../lib/globalData';

const { Paragraph } = Typography;
const { Panel } = Collapse;
const { Content } = Layout;

export default function Faq() {
  return (
    <>
      <PageHeader title="FAQ" />
      <Content className={faqStyles.container}>
        <Paragraph type="secondary" className={baseStyles.subTitle}>Find answers to your frequently asked questions here.</Paragraph>
        <Collapse className={baseStyles.collapse} defaultActiveKey={['0']} accordion>
        <Panel header="What is CoinRotator?" key="0">
          CoinRotator is a proprietary crypto market coin screener for the top 1000+ crypto coins. When you land on the homepage you will see the coins ranked by market cap. Each coin will have an <UpTag /> <DownTag /> or <HodlTag /> trend. This is determined once daily at 01:00 UTC. The trends are generated by checking their relative strength against BTC ETH and USDT. If an altcoin is stronger than these three it will be an <UpTag /> trend, if it is weaker it is a <DownTag /> trend. And if it is inconclusive the trend generated is <HodlTag /> trend.
        </Panel>
        <Panel header="How do you use CoinRotator?" key="1">
          <p>There are several ways CoinRotator will become an indispensable part of your daily Crypto trading routine.</p>
          <ol>
            <li>Check for new trends daily in order to buy into coins which are outperforming BTC ETH and USDT. After checking the Market Health <Link href="/market-health">here</Link>, general health of the market (BTCUSD), you can take a position and check its performance daily. The CoinRotator screener currently updates once per day at 01:00 UTC.</li>
            <li>Search your favorite altcoin in the top 1000+ (based on market cap) and see if it is a <UpTag /> <DownTag /> and <HodlTag /> trend. Consider your time horizon and profit expectations. If you are in profit, consider taking some profits based on what the CoinRotator trend streak or market health.</li>
            <li>Seek out undervalued low marketcap coins by applying advanced settings in the filter. Choose &lt;100m and trend streak 1-5 and select UP only. Here will be a screen result of the <Link href="/low-market-cap">best performing low marketcap coins</Link> in the top 1000. Be warned, these coins are more volatile than the top ranked coins but if BTC behaves you are likely to see much larger gains.</li>
            <li>Check out our explainer video for more details</li>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/OcyZcip24pM" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
          </ol>
        </Panel>
        <Panel header="Does CoinRotator work in bear markets?" key="2">
          Yes! CoinRotator provides three forms of trends. <UpTag />, <HodlTag />, and <DownTag />. When Bitcoin is weak, down trends are better than up trends. Be advised shorting crypto is as risky as it gets. You can lose more than your entire investment if you are overleveraged.
        </Panel>
        <Panel header="What are Trends based on?" key="3">
          Primarily on the SuperTrend indicator. CoinRotator&apos;s default settings are faster than the respective indicator found on Tradingview. In addition we track the performance of altcoins against BTC ETH and USDT. An &quot;actionable&quot; trend is only generated if all three markets are in agreement. If not, a <HodlTag /> trend is issued.
        </Panel>
        <Panel header="How accurate are Trends?" key="4">
          They are not designed to be a complete trading system. You&apos;ll need to check the trend health of the overall market before taking any position (we built a <Link href="/market-health">Market Health oscillator</Link> to asses the overall market conditions). Also, check out the X feed for your chosen coin (found on the coin pages), and then check the trend staus of BTC. If things look positive (or excessively negative, for that matter), it&apos;s a likely winner.
        </Panel>
        <Panel header="How to Apply the Supertrend indicator to the Coin Page Chart?" key="5">
          <ol className={faqStyles.imageList}>
            { /* eslint-disable @next/next/no-img-element */ }
            <li>Click on indicators<img src="/supertrend1.png" alt="Click on indicators"/></li>
            <li>Type Supertrend<img src="/supertrend2.png" alt="Type &apos;SuperTrend&apos;" /></li>
            <li>Change settings to ATR length 5 and Factor to 1.5 for CoinRotator settings.<img src="/supertrend3.png" alt="Change the settings" /></li>
            { /* eslint-enable @next/next/no-img-element */ }
          </ol>
          If you prefer to use the default Supertrend settings in the screener you can do so in the advanced filter in the &quot;customize&quot; setting on each page.
        </Panel>
        <Panel header="Do you have any backtest data?" key="6">
          We have personal experience with these trends for several years in the crypto market. They work, but not as a stand-alone system. They are very powerful as a filtering mechanism (don’t fight the trend). We will begin publishing individual market performance for each altcoin in Q1 2024.
        </Panel>
        <Panel header="Can we access your API?" key="7">
          Q1 2024
        </Panel>
        <Panel header="Why does my coin say &apos;Up&apos;, but it&apos;s down a lot today?" key="8">
          Coinrotator issues trends once a day after the daily bar closes at 01:00 UTC. The price must violate the price threshold and stay at that point after this time.
          Once that happens the trends will reverse. At present, we strongly discourage blindly following the trend alerts based on the coin screener.
          If you want a faster trend analysis you can access our 4hr alerts in our <a href="https://discord.com/invite/zfnxHyrhSK">discord</a>.
          For even more advanced real-time analysis please check out the <a href="https://www.tradingview.com/script/yNrotMjf-CoinRotator">CoinRotator Trading View Indicator</a>.
        </Panel>
 <Panel header="Why do you use the word HODL in your signals?" key="9">
          HODL is a misspelling of a very enthusiastic early holder in Bitcoin. The term stuck and has been used ever since. In the spirit of early adoption and the culture surrounding the revolutionary nature of crypto, we have adopted it to describe an uncertain near-term situation in that coin.
        </Panel>
<Panel header="Does CoinRotator have a token?" key="10">
      No, CoinRotator doesn&apos;t have a token. If you come across a token or pre-sale claiming to be related to CoinRotator then it&apos;s likely a scam. Remember to always be cautious and do your own research before investing in any tokens on pre-sales.
        </Panel>

<Panel header="Where does CoinRotator get data from?" key="11">

CoinRotator gets data from popular APIs such as CoinGecko, CoinPaprika, Coinmarketcap and some as yet to be revealed sources. As we scale, we will begin running nodes to specific chains to enhance our data and charting options. At some point, we will offer our own API solutions, so stay tuned.
        </Panel>
<Panel header="Is there a CoinRotator app?" key="12">
No, we are looking into the possibility though. You can always bookmark the webapp on your mobile or desktop screen (like friend.tech)
    </Panel>
<Panel header="Does CoinRotator have Telegram bots?" key="13">

Yes! CoinRotator Daily Trend Alerts Bot is <a href="https://t.me/+JvnH0f34vMw0ZTY8">here</a> In addition to providing links to fresh trend changes, it has daily lists you can export to TradingView if you have a paid account.
If you prefer you can always bookmark <a href="https://coinrotator.app/todays-trends">crypto trends for today</a> and check back each day for updates.
    </Panel>
<Panel header="Does CoinRotator have Discord bots?" key="14">

Yes! We have a Coinrotator Discord bot as well. If this link has expired, please message us directly on X @coinrotatorapp
The discord has the Daily Trend Alerts as well as the 4hr signals sorted by sector.

    </Panel>
<Panel header="Token Listing Questions" key="15">
You can use the search bar to search for any particular token by its name, symbol, or address, as well as a pair address.

How do I update information about a token, such as description and social links?

CoinRotator automatically looks for token information from external token lists, such as CoinGecko&apos;s. Once a token is present on such a list, all of its information will be displayed on CoinRotator automatically. If we have missed something for your favorite project, you can always reach out to us @coinrotatorapp

How does CoinRotator calculate a token&apos;s FDV and Market Cap?

CoinRotator uses the following formula to calculate fully diluted valuation for any given token:

FDV = (total supply - burned supply) * price

For tokens that don&apos;t burn supply that isn&apos;t in circulation, CoinRotator will look for self-reported circulating supply from CoinGecko, and automatically use that amount to calculate market cap instead.

Token Listing Issues

All tokens that have been in the top 1500 marketcap on CoinGecko in the past two years are automatically tracked in the CoinRotator database and are updated through our provider&apos;s APIs. However, some new projects may not self-report their market cap or FDV to CoinGecko, in which case CoinRotator may mistakenly omit these projects from its screener.


    </Panel>
<Panel header="How to Add a Dex Listing?" key="16">

For supported chains and protocols, CoinRotator will track all DEXes automatically, regardless of whether they are listed or not.

Please reach out to us at @coinrotatorapp to request a DEX listing, but keep in mind that DEXes with low liquidity and volume may not be listed at all.

Here are some of the factors we consider before listing a new DEX:
The DEX has a significant amount of liquidity and daily volume.
The DEX has open-sourced and audited smart contracts.
The DEX has an active community and user base.

   </Panel>

<Panel header="CoinRotator Advertising" key="17">

All advertising-related inquiries are managed by a third-party team, which is the premier advertising network in the cryptocurrency market, they serve as our only authorized representative.

To advertise on our website, both individuals and companies must complete this company&apos;s external verification process, which includes KYC, prior to launching their campaigns. Please keep in mind that even if the process is completed successfully, we and our partner reserve the right to not promote the project on Coinrotator.

You can obtain additional information and a quote for advertising services on our website by contacting @coinrotatorapp and we will reveal the third party.

Please note that it may take up to 24 hours during business hours and up to 72 hours during holidays and weekends to receive a response. Alternative communication channels such as Telegram or Skype are also available and will be confirmed via email to prevent impersonation.
   </Panel>
        </Collapse>
      </Content>
    </>
  );
}

export async function getStaticProps() {
  const appData = await globalData();

  return { props: { appData } };
}
