import { Breadcrumb, Typography, Layout } from 'antd';
import Link from 'next/link'

import baseStyles from '../styles/base.module.less'
import tcStyles from '../styles/terms.module.less'
import globalData from '../lib/globalData';

const { Title, Paragraph } = Typography;
const { Content } = Layout;

export default function Terms() {
  return (
    <Content className={baseStyles.container}>
      <Breadcrumb className={baseStyles.breadcrumbs}>
        <Breadcrumb.Item><Link href="/"><a>Home</a></Link></Breadcrumb.Item>
        <Breadcrumb.Item>Terms</Breadcrumb.Item>
      </Breadcrumb>
      <Title className={tcStyles.title}><span className={tcStyles.bold}>CoinRotator&nbsp;</span>Terms of Use</Title>
      <Paragraph className={tcStyles.paragraph}>These Terms of Use (the &quot;Terms&quot;) govern your access to and use of this website, CoinRotator (the &quot;Website&quot;), and associated content, software and applications (collectively, the &quot;Service&quot;). These Terms also include our Privacy Policy, which is located at <Link href="https://CoinRotator/terms"><a>CoinRotator/terms</a></Link>.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>The Service is administered and maintained by CoinRotator. The terms &quot;we&quot;, &quot;us&quot; and &quot;our&quot; also refer to CoinRotator. The term &quot;you&quot; refers to the person visiting this Website.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>Please read these Terms carefully. They contain important information regarding your legal rights, including limitations on CoinRotator&apos;s and certain third parties&apos; liability, disclaimers of warranties and a submission to jurisdiction. Each time you access the Service by any means (for example, through the Internet or on a mobile device), you irrevocably agree to comply with the version of the Terms posted on this Website at the time you access this Website. You may not use the Service if you do not agree to these Terms.</Paragraph>
      <Title level={2} className={tcStyles.subtitle}>Eligibility</Title>
      <Paragraph className={tcStyles.paragraph}>To access or use the Service, you must be at least 13 years old. The Service is strictly for your personal, non-commercial use unless you enter into a separate agreement with us for your commercial use.</Paragraph>
      <Title level={2} className={tcStyles.subtitle}>License</Title>
      <Paragraph className={tcStyles.paragraph}>You may only use the Service as expressly permitted by these Terms. All rights not expressly granted to you are reserved by CoinRotator, its third-party providers and other respective owners, if any.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>CoinRotator provides content through the Service that is copyrighted and/or trademarked work of CoinRotator or CoinRotator’s third-party licensors and suppliers (collectively, the &quot;Content&quot;). For clarity, Content shall include all such content accessed by you at any time. You acknowledge that the Service has been developed, compiled, prepared, revised, selected, and arranged by CoinRotator and such third parties through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort, and money and constitutes valuable intellectual property of CoinRotator and such others. Accordingly, you shall protect the proprietary rights of CoinRotator and all others having rights in the Service during and after the term of this agreement and comply with all reasonable written requests made by CoinRotator to protect its and others’ contractual, statutory, and common law rights in the Service.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>You agree not to use the Service or any of the Content for any commercial purpose. Except for the foregoing license, you have no other rights to the Service or any Content, and you may not modify, edit, copy, distribute, reproduce, publish, display, perform, license, sell, rent, lease, loan, create derivative works of, create any index, reverse engineer, alter, enhance, provide access to or in any way exploit the Service or Content in any manner.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>If you breach any of these Terms, the above license will terminate automatically.</Paragraph>
      <Title level={2} className={tcStyles.subtitle}>Prohibited Activities</Title>
      <Paragraph className={tcStyles.paragraph}>You agree that you will not:</Paragraph>
      <ul className={tcStyles.list}>
        <li>Copy, modify or create derivative works of the Service or any Content;</li>
        <li>Copy, manipulate or aggregate any Content (including data) for the purpose of making it available to any third party;</li>
        <li>Trade, sell, rent, loan, lease or license any Content or access to the Service, whether commercially or free of charge;</li>
        <li>Use or introduce to the Service any data mining, crawling, &quot;scraping&quot;, robot or similar automated or data gathering or extraction method, or manually access, acquire, monitor or copy any portion of the Service, or download or store Content (unless expressly authorized by CoinRotator). Certain data and other information within the Service is available by subscription, or for a fee, at hello@CoinRotator</li>
        <li>Make excessive requests for information or take any action that interferes with, disrupts or imposes an undue burden on the Service or any server or network connected to the Service or negatively affects the quality or availability of any Content, or speed or functionality of the Service;</li>
        <li>Introduce a virus, Trojan horse, worm, time bomb or other malware to the Service, or use any device, software or routine to bypass any software or hardware that prohibits volume requests for information;</li>
        <li>Violate, bypass or circumvent any security measure intended to limit or prevent access to the Website, Content or Service; or otherwise attempt to gain unauthorized access to the Service, any Content or to any computer systems or networks connected to the Service or any CoinRotator server, whether through hacking, password mining, unauthorized use of another&apos;s password/credentials or any other means;</li>
        <li>Restrict, inhibit or interfere with use of the Service by any other user (including by hacking or defacing the Website);</li>
        <li>Introduce or otherwise distribute through the Website any computer program that damages, interferes with, intercepts, collects, releases or discloses any system, data or personal information of ours or any third party;</li>
        <li>Make use of any of our trademarks, service marks, trade names or logos or those of any third party displayed on the Website; or modify or remove any copyright or other proprietary notice in the Content;</li>
      </ul>
      <Paragraph className={tcStyles.paragraph}>Additionally, you acknowledge and agree that you (and not CoinRotator) are responsible for obtaining and maintaining all telecommunications, broadband, and computer hardware, equipment, software and services needed for you to access and use the Service, and paying all charges related thereto.</Paragraph>
      <Title level={2} className={tcStyles.subtitle}>Ownership and Intellectual Property</Title>
      <Paragraph className={tcStyles.paragraph}>Subject to these Terms, you may view, print and make copies of Content for your own personal use. You may not, and shall not, copy, reproduce, download, &quot;screen scrape&quot;, store, transmit, broadcast, publish, modify, create a derivative work from, display, perform, distribute, redistribute, sell, license, rent, lease or otherwise use, transfer (either in printed, electronic or other format) or exploit any Content, in whole or in part, in any way that does not comply with these Terms without our prior written permission. To request permission to use any Content other than as expressly permitted in these Terms, please contact hello@CoinRotator.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>As between CoinRotator and you, all Content is owned or controlled by CoinRotator. CoinRotator, its logo, and, except as noted below, all other product or service names or slogans displayed on the Service are registered and/or common law trademarks of CoinRotator or its suppliers or licensors and may not be copied, imitated, or used, in whole or in part, without the prior written permission of CoinRotator or the applicable trademark holder. In addition, the look and feel of the Service, including all page headers, custom graphics, button icons, and scripts, is the service mark, trademark, and/or trade dress of CoinRotator and may not be copied, imitated, or used, in whole or in part, without the prior written permission of CoinRotator. Nothing contained in these Terms grants you any interest in any of CoinRotator&apos;s or any third-party&apos;s intellectual property.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>The use or misuse of CoinRotator’s trademarks or other intellectual property, except as expressly permitted by these Terms, is prohibited. You shall promptly notify CoinRotator at hello@CoinRotator if you know or suspect that any of CoinRotator&apos;s or its providers&apos; intellectual property rights has been violated or infringed.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>&quot;CoinRotator&quot; and all related logos, trademarks, service marks and trade names are solely the property of CoinRotator. The absence of a name, logo or other mark herein does not constitute a waiver of any and all intellectual property rights that CoinRotator has established. Other trademarks, names or logos used on the Website are property of their respective owners. You are not authorized to use any of the foregoing.</Paragraph>
      <Title level={2} className={tcStyles.subtitle}>Linking to the Service from Your Website</Title>
      <Paragraph className={tcStyles.paragraph}>You may place one or more links to the Service (collectively, the &quot;Link&quot;) on your own website (&quot;Your Site&quot;), provided that:</Paragraph>
      <ol className={tcStyles.list}>
        <li>The Link shall display only the following text: &quot;CoinRotator&quot; or &quot;CoinRotator&quot; or &quot;Link to CoinRotator&quot;;</li>
        <li>Your Site shall not contain any content that is unlawful, threatening, abusive, libelous, defamatory or otherwise inappropriate, as determined by us in our sole discretion;</li>
        <li>The look and feel of all content that accompanies the Link or is on the same page as the Link (for example, the entire article in which the Link appears, even if it is not all on the same page as the Link) shall not otherwise be of a nature that may damage or dilute the goodwill associated with CoinRotator&apos;s name, reputation or any of its trademarks, trade names or service marks, as determined by CoinRotator in its sole discretion; and</li>
        <li>No content on Your Site shall contain any information that, in our sole discretion, may create the false impression that you, Your Site or any other website, service, person or entity is associated with, sponsored by or otherwise endorsed by CoinRotator, or that any activity engaged in by you or anyone else has been approved by CoinRotator.</li>
      </ol>
      <Paragraph className={tcStyles.paragraph}>We may revoke our consent to a Link at any time, without prior notice. If we notify you that you may no longer link to the Service, or to a page or document, you must promptly (and, in any event, within three (3) business days) remove all affected Links from Your Site.</Paragraph>
      <Title level={2} className={tcStyles.subtitle}>Feedback</Title>
      <Paragraph className={tcStyles.paragraph}>If you send or transmit any communication, including but not limited to feedback, questions, comments or suggestions to CoinRotator, whether by letter, email, telephone or otherwise (collectively, &quot;Feedback&quot;), all such Feedback is, and will be treated as non-confidential and non-proprietary. You hereby assign to CoinRotator all right, title, and interest in, and CoinRotator is free to use, without any attribution or compensation to you, any ideas, concepts, know-how or techniques or other intellectual property and proprietary rights contained in the Feedback, whether or not patentable, for any purpose whatsoever, including but not limited to enhancing the Service, or otherwise developing, manufacturing, licensing, marketing and selling products and services based on or containing such Feedback. You also understand and agree that CoinRotator is not obligated to use, display, reproduce, or distribute any such ideas, know-how, concepts, or techniques contained in the Feedback, and you have no right to compel such use, display, reproduction, or distribution. CoinRotator may use aggregated and statistical data derived from Website usage.</Paragraph>
      <Title level={2} className={tcStyles.subtitle}>Disclaimers and Limitation of Liability</Title>
      <Paragraph className={tcStyles.paragraph}>THE CONTENT ON THE SERVICE IS STRICTLY FOR INFORMATIONAL PURPOSES. NOTHING ON OR IN THE SERVICE SHALL CONSTITUTE OR BE CONSTRUED AS AN OFFERING OF ANY CURRENCY OR ANY FINANCIAL INSTRUMENT OR AS INVESTMENT ADVICE OR INVESTMENT RECOMMENDATIONS (SUCH AS RECOMMENDATIONS AS TO WHETHER TO PURCHASE A CURRENCY OR INSTRUMENT) BY COINROTATOR OR A RECOMMENDATION AS TO AN INVESTMENT STRATEGY BY COINROTATOR. CONTENT ON THIS SERVICE SHOULD NOT BE CONSIDERED AS INFORMATION SUFFICIENT UPON WHICH TO BASE AN INVESTMENT STRATEGY. NO CONTENT ON THE SERVICE IS TAILORED TO THE SPECIFIC NEEDS OF ANY INDIVIDUAL, ENTITY OR GROUP OF INDIVIDUALS. COINROTATOR EXPRESSES NO OPINION AS TO THE FUTURE OR EXPECTED VALUE OF ANY CURRENCY, SECURITY OR OTHER INTEREST. CoinRotator DOES NOT EXPLICITLY OR IMPLICITLY RECOMMEND OR SUGGEST ANY INVESTMENT STRATEGY OF ANY KIND. CONTENT ON THE SERVICE MAY NOT BE USED AS A BASIS FOR ANY FINANCIAL OR OTHER PRODUCT WITHOUT THE EXPRESS PRIOR WRITTEN CONSENT OF COINROTATOR.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>The Content provided on the Service is submitted to CoinRotator by unrelated third-party providers. CoinRotator does not review all Content for accuracy, does not review Content for completeness or reliability, and does not warrant or guarantee the accuracy, completeness, reliability or any other aspect of any Content.</Paragraph>
      <Paragraph className={tcStyles.paragraph}></Paragraph>
      <Title level={2} className={tcStyles.subtitle}>Linking to the Service from Your Website</Title>
      <Paragraph className={tcStyles.paragraph}>THE SERVICE AND THE CONTENT PUBLISHED WITHIN THE SERVICE MAY INCLUDE INACCURACIES OR ERRORS. COINROTATOR DOES NOT GUARANTEE THE ACCURACY, COMPLETENESS, TIMELINESS, SECURITY, AVAILABILITY OR INTEGRITY OF THE SERVICE OR ANY CONTENT, AND DISCLAIMS ALL LIABILITY FOR ANY ERRORS OR OTHER INACCURACIES RELATING TO THE SERVICE OR THE CONTENT. COINROTATOR MAKES NO REPRESENTATIONS ABOUT THE SUITABILITY OF THE SERVICE OR ANY CONTENT, OR THAT THE SERVICE OR CONTENT WILL BE UNINTERRUPTED OR OPERATE IN COMBINATION WITH ANY SOFTWARE, SERVICE, SYSTEM OR OTHER DATA OR INFORMATION. THE SERVICE AND ALL CONTENT ARE PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND. COINROTATOR DISCLAIMS ALL WARRANTIES AND CONDITIONS THAT THIS SERVICE, ITS SERVERS, OR ANY EMAIL SENT FROM COINROTATOR, ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. COINROTATOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH REGARD TO THE SERVICE AND THE CONTENT, INCLUDING ALL IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NONINFRINGEMENT.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, COINROTATOR ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF ANY CONTENT; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF THE SERVICE; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS AND/OR ANY AND ALL INFORMATION STORED THEREIN; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICE; (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH THE SERVICE BY ANY THIRD PARTY; (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE SERVICE; AND/OR (VII) THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>IN NO EVENT SHALL CoinRotator (AND ITS RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, MEMBERS, AGENTS, AND AFFILIATES) BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR DAMAGES FOR LOST PROFITS, ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, YOUR ACCESS TO OR USE OF THE SERVICE OR WITH THE DELAY OR INABILITY TO ACCESS, DISPLAY, OR USE THE SERVICE; ANY COMPUTER VIRUSES, INFORMATION, SOFTWARE, LINKED SERVICES, PRODUCTS, AND SERVICES OBTAINED THROUGH THE SERVICE; OR OTHERWISE ARISING OUT OF THE ACCESS TO OR USE OF THE SERVICE WHETHER BASED ON A THEORY OF NEGLIGENCE, CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, AND EVEN IF COINROTATOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT SHALL COINROTATOR (AND ITS RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, MEMBERS, AGENTS, AND AFFILIATES) BE LIABLE TO YOU FOR ANY CLAIMS, PROCEEDINGS, LIABILITIES, OBLIGATIONS, DAMAGES, LOSSES OR COSTS IN EXCESS OF $100.00. THE LIMITATION OF LIABILITY REFLECTS THE ALLOCATION OF RISK BETWEEN THE PARTIES. THE LIMITATIONS SPECIFIED IN THIS SECTION WILL SURVIVE AND APPLY EVEN IF ANY LIMITED REMEDY SPECIFIED IN THESE TERMS IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. THIS AGREEMENT GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY FROM STATE TO STATE. THE DISCLAIMERS, EXCLUSIONS, AND LIMITATIONS OF LIABILITY UNDER THIS AGREEMENT WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</Paragraph>
      <Title level={2} className={tcStyles.subtitle}>Indemnification</Title>
      <Paragraph className={tcStyles.paragraph}>Except to the extent prohibited under applicable law, you shall indemnify, defend and hold harmless CoinRotator and its members, managers, directors, officers, employees, partners, sponsors, consultants, contractors, service providers, agents, successors and assigns from and against any and all suits, actions, proceedings and claims by third parties (whether threatened or actual), and all losses, liabilities, damages, judgments, costs and expenses (including reasonable attorneys&apos; fees) arising out of, relating to or in connection with: (i) your use (or misuse) of and access to the Service or Content; (ii) your violation of any of these Terms; (iii) your violation of any applicable law, rule or regulation; (d) any claim that any information provided by you to CoinRotator in connection with the Website, including the Content, caused damage to, infringed upon, misappropriated or otherwise violated the rights of any third party, including infringement, misappropriation or other violation of third-party intellectual property rights, or violation of any right of privacy or publicity; and/or (iv) any dispute that you have with any third party relating to or in connection with the Service or Content. CoinRotator reserves the right, at its own cost, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with CoinRotator in asserting any available defenses and in the conduct of such defense.</Paragraph>
      <Title level={2} className={tcStyles.subtitle}>Third Party Websites</Title>
      <Paragraph className={tcStyles.paragraph}>The Service may contain links to third-party websites. Your use of all links to third-party websites is at your own risk. We do not monitor or have any control over, and make no claim or representation regarding third-party websites. To the extent such links are provided by us, they are provided only as a convenience, and a link to a third-party websites does not imply our endorsement, adoption or sponsorship of, or affiliation with, such third-party websites. When you leave the Website, whether via a link contained on the Website or through the use of your web browser or other navigational tool, the information you view is not provided by us. Our terms and policies do not govern your use of third-party websites. We are not responsible for, have no control over and do not monitor or review the content of any other website. A link to a third-party website does not imply sponsorship, approval, affiliation or endorsement by CoinRotator of the linked third-party website or of that third party&apos;s products or services.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>YOU AGREE THAT COINROTATOR WILL NOT, UNDER ANY CIRCUMSTANCES, BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY GOODS, SERVICES, INFORMATION, RESOURCES AND/OR CONTENT AVAILABLE ON OR THROUGH ANY THIRD-PARTY WEBSITE OR SERVICES, FOR ANY DEALINGS OR COMMUNICATIONS YOU MAY HAVE WITH THIRD PARTIES, OR FOR ANY HARM, DAMAGES OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH ANY OF THE FOREGOING OR YOUR USE OF OR RELIANCE ON THE MATERIALS OR THE CONTENT OR BUSINESS PRACTICES OF ANY THIRD PARTY.</Paragraph>
      <Title level={2} className={tcStyles.subtitle}>Modification of the Website</Title>
      <Paragraph className={tcStyles.paragraph}>At any time and in CoinRotator&apos;s sole discretion, CoinRotator may (in whole or in part) modify, suspend or discontinue the Service and/or any Content without notice, for any reason. We shall have no liability to you or to any third party for any such modification, suspension or discontinuance.</Paragraph>
      <Title level={2} className={tcStyles.subtitle}>Changes to these Terms</Title>
      <Paragraph className={tcStyles.paragraph}>We may revise these Terms from time to time, without prior notice. You are bound by any changes to these Terms upon our posting of such changes on the Service. You should check these Terms often to make certain that you are aware of the most current Terms.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>You acknowledge that any breach of either of the sections above titled &quot;Prohibited Activities&quot; or &quot;Ownership and Intellectual Property&quot; would cause immediate and irreparable harm to CoinRotator, for which monetary damages would not be sufficient, and that, in addition to all other remedies available to CoinRotator at law or in equity, CoinRotator shall be entitled to seek injunctive relief without proof of damages or the posting of bond or other security in the event of such a breach or threatened breach.</Paragraph>
      <Title level={2} className={tcStyles.subtitle}>General</Title>
      <Paragraph className={tcStyles.paragraph}>These Terms (and any other terms or agreements referenced herein, including our Privacy Policy, which is located at CoinRotator/terms), constitute the entire agreement between you and CoinRotator relating to your use of the Service and supersede all prior or contemporaneous communications, whether electronic, oral or written, between you and CoinRotator with respect to the Service. A printed version of these Terms and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to these Terms to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>You agree that no joint venture, agency, partnership, or employment relationship exists between you and CoinRotator and/or its affiliates as a result of these Terms or use of the Service.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>In no event shall CoinRotator be responsible or liable for any failure or delay in the performance of its obligations hereunder arising out of or caused by, directly or indirectly, forces beyond its control, including, without limitation, strikes, work stoppages, accidents, acts of war or terrorism, civil or military disturbances, nuclear or natural catastrophes or acts of God, and interruptions, loss or malfunctions of utilities, communications or computer (software and hardware) services.</Paragraph>
      <Paragraph className={tcStyles.paragraph}>Any heading or section title contained herein is for convenience of reference only and shall not affect the meaning or interpretation of these Terms. The terms &quot;include&quot; and &quot;including&quot; are deemed to include the phrase &quot;without limitation&quot; immediately thereafter.</Paragraph>
    </Content>);
}

export async function getStaticProps() {
  const appData = await globalData();

  return { props: { appData } };
}